noise_data_dict = [
    'AutoDrv.Long.Gen.DistPreview',
    'AutoDrv.Long.Gen.DistStand',
    'AutoDrv.Long.Gen.AccMax',
    'AutoDrv.Long.Gen.DecComf',
    'AutoDrv.Long.Gen.PCtrlSpd',
    'AutoDrv.Long.Gen.TimeGap',
    'AutoDrv.Long.Gen.TAdaptDist',
    'AutoDrv.Long.Gen.TAdaptRelSpd_low',
    'AutoDrv.Long.Gen.TAdaptRelSpd_high',
    'AutoDrv.Long.Gen.RelSpdRef',
    'AutoDrv.Long.Gen.DecMax',
    'AutoDrv.AccLatMax',
    'AutoDrv.Cautious',
    #'AutoDrv.Long.Junction.Param',
    'LVD.AxMax',
    'LVD.vMax' ,
    'LVD.Pmax',
    'LVD.tBuildUp',
    #'AutoDrv.Lat.HDMbased.Param',
]